version: "3"

services:
        dice:
           build: /opt/dice/

        gateway:
           build: /opt/gateway
           ports:
               - "127.0.0.1:5000:5000"
           depends_on:
                   - dice
